spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    data: classpath:data-h2.sql
  h2:
    console:
      enabled: true

logging.level.org.springframework.batch: DEBUG
